# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
        name: black (python)
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.285
    hooks:
    -   id: ruff
        name: ruff (python)
        args: [--fix]
        types_or: [python, jupyter]
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
        args: [--filter-files]
        types_or: [python, jupyter]
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.2.0
    hooks:
    -   id: autoflake
        name: autoflake (python)
        types_or: [python, jupyter]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
    -   id: mypy
        name: mypy (python)
        args: [--enable-incomplete-feature=Unpack]
        types: [python, jupyter]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
        -   id: check-json
        -   id: check-added-large-files
