# This is a basic workflow to help you get started with Actions

name: dispatched E2E testing (data-transfer)

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      flag_1:
        type: boolean
        description: boolean flag
        required: true
        default: true
      flag_2:
        type: boolean
        description: boolean flag
        required: true
        default: true

jobs:
  sample:
    name: sandbox
    runs-on: ubuntu-latest
    env:
      FLAG: ${{ github.event.inputs.flag }}
    steps:
      - name: step 1
        if: always() && github.event.inputs.flag_1 == 'true'
        run: |
          echo "step 1"
      - name: step 2
        if: always() && github.event.inputs.flag_2 == 'true'
        run: |
          echo "step 2"
