# This is a basic workflow to help you get started with Actions

name: sandbox

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      flag_1:
        type: boolean
        description: flag 1
        required: true
        default: true
      flag_2:
        type: boolean
        description: flag 2
        required: true
        default: true
      option_1:
        type: choice
        description: option 1
        required: true
        options:
          - any
          - foo
          - bar
        default: any

jobs:
  sample:
    name: sandbox
    runs-on: ubuntu-latest
    env:
      FLAG_1: ${{ inputs.flag_1 }}
      FLAG_2: ${{ github.event.inputs.flag_2 }}
    steps:
      - name: step 0
        run: |
          echo "step 0"
          echo $FLAG_1
          echo $FLAG_2
          echo ${{inputs.option_1}}
      - name: step 1
        if: ! ${{ inputs.flag_1 }}
        run: |
          echo $FLAG_1
      - name: foo
        if: always() && (inputs.option_1 == 'any' || inputs.option_1 == 'foo')
        run: |
          echo $FLAG_1
          echo "step 1"
      - name: bar
        if: always() && (inputs.option_1 == 'any' || inputs.option_1 == 'bar')
        run: |
          echo $FLAG_2
          echo "step 2"
